### ISSUE TITLE
Determine Terms of Service for using the API

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#1]
Need to determine the terms of service for anyone using the API. It should include a list of activities that is not permitted and the consequence of doing it. This will likely include limitations of liability and indemnity, which is especially important for this project.

Need to loop-in legal to discuss.

A couple of examples of City of Chicago terms of service include the [Open311 API](http://dev.cityofchicago.org/docs/open311/tos/) and the [data portal](https://www.cityofchicago.org/city/en/narr/foia/data_disclaimer.html).

**Comment by RaedMan** [comment]
I'll work on integrating the [Open311 API](http://dev.cityofchicago.org/docs/open311/tos/) terms of service with what Allison sent from this first draft:

_"This information is meant to aid clinical reasoning. No medical decision should be based solely on information provided by this program. By using this information, the user shall indemnify and hold harmless the developers of this program from and against any claims, demands, or causes of action whatsoever."_

**Comment by tomschenkjr** [comment]
Thanks. The Open311 docs provide a nice outline. We can update and modify (if needed) each section.



_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org


________________________________

**Comment by RaedMan** [comment]
Regarding Issue #10 Specify that predictions are for kids under 1, it may be better handled under Terms of Service, since under #2 Eligibility criteria & process for new institutions, hospitals sign off that they read it. The following is draft language and possibly @potash and @AOCjcarr can add some more detail for clarity:

Pediatricians are directed to test every Chicago child’s blood for lead and report high levels to the Chicago Department of Public Health (CDPH). According to the Centers for Disease Control and Prevention ([CDC](https://www.cdc.gov/nceh/lead/acclpp/blood_lead_levels.htm)), the reference level of 5 micrograms/dL should be used to identify children with elevated blood lead levels and is based on U.S. children between the ages of 1 - 5 years old based on the 97.5th percentile of the National Health and Nutrition Examination Survey of blood lead distribution in children.

Though lead is no longer used in paint, plumbing, gasoline and a myriad of other products in the United States, Chicago’s older housing stock creates a persistent problem as homes built prior to 1978 that have not been properly maintained may still have older paint that can result in exposure to lead in children. This is especially true in some communities on the south and west sides of Chicago.

To ensure success in the fight against lead poisoning, this project is part of CDPH's overall plan to provide concrete steps that are being taken by the department and its partners to further reduce and eventually eliminate lead poisoning in Chicago’s children.

This lead safe predictive model helps identify infants at risk of being lead poisoned in homes with lead paint. The model provides an opportunity to prevent lead paint exposure through high priority proactive home lead inspections and blood testing at an earlier age. The predictive model combines data from multiple sectors including public health, census, buildings and the county assessor’s office to create real-time interfaces that identify where at-risk children live. 

The risk score, defined as ( @potash to complete when known) will be sent to health centers through electronic health records (EHR) and physicians will have the opportunity to be alerted to either order a blood lead test and/or request to visually inspect the homes of either their **pregnant patients (is this still doable?)** and their at-risk children for lead paint hazards.

If the visual inspection determines that there is a risk of lead poisoning due to paint, the CDPH Healthy Homes and Lead Prevention Program lead inspectors schedule a visit and examine for potential lead paint hazards. Trained and licensed CDPH inspectors assess these homes to identify lead-based paint hazards and work with the property owners to ensure the hazards are fixed. CDPH Inspectors support this by offering free lead-safe work practices classes in both English and Spanish, or face fines and a referral to Circuit Court. Through grants made available by the U.S. Department of Housing and Urban Development (HUD) and the Cook County Department of Public Health, CDPH, in cooperation with Neighborhood Housing Services, provides 100% financial assistance to fix lead-based paint hazards in eligible homes. A unique aspect of the HUD grant is that tenants can apply. Since 2003, CDPH has helped ensure lead hazards have been fixed in more than 2,800 homes. CDPH has also launched a community outreach program aimed at providing additional information to residents in communities facing a disproportionate number of lead poisoning cases. As part of this program, CDPH is working with Imagine Englewood If and the Metropolitan Tenants Organization to provide education and information to pregnant women and families with young children as well as perform visual inspections by trained staff.

This prediction model is only for infants (defined as 0-1 year of age), thus risk scores will be provided only to infants under one year of age. According to the [CDC](https://www.cdc.gov/nceh/lead/acclpp/blood_lead_levels.htm), "by shifting our focus to primary prevention of lead exposure, we can reduce or eliminate dangerous lead sources in children’s environments before they are exposed." Reference "[Preventing Lead Exposure in Young Children: A Housing Based Approach to Primary Prevention of Lead Poisoning](https://www.cdc.gov/nceh/lead/publications/primarypreventiondocument.pdf)."

This information is meant to aid clinical reasoning. No medical decision should be based solely on information provided by this program. By using this information, the user shall indemnify and hold harmless the developers of this program from and against any claims, demands, or causes of action whatsoever.

**Comment by tomschenkjr** [comment]
@RaedMan - please use [this link](https://github.com/Chicago/lead-safe-api-docs/blob/issue1/docs/tos.md) and edit the page to insert the terms of service language. I've added some example text for you to follow the formatting. Click on the pencil button to edit. Use the "Preview Changes" to see how it is rendering. Don't worry too much about formatting -- we can always clean that up.

When you're finished, enter a brief message and click "Commit Changes" to submit the edits.

**Comment by tomschenkjr** [comment]
Great. I've incorporated the language and it's currently on the `dev` branch. As we finish other work, we'll incorporate everything else into the webpage.

The application page mentions the "eligibility criteria". Is that going to be in the Terms of Service or a separate page?

**Comment by RaedMan** [comment]
Probably easier to navigate if all on one page with two separate major headings but with teh bookmarks remaining as is so they can navigate easily between the two. I have not written the eligibility, but I think the form says it all: Must be a hospital as defined, must have a clinician as defined, must have tech as defined, must have an EHR system that can be accessed, must have funding, etc.

For TOS, I'm awaiting clearance from CDPH on that current language then HIPAA Officer needs to review it before going to law. I do want to add that the API cannot be used to publish maps, public research, make public the aggregate data using the model, etc.

**Comment by tomschenkjr** [comment]
Yeah, it’s easy to navigate to a subheading. Once you’re ready with eligibility requirements, please add those and I can incorporate it.
