### ISSUE TITLE
Response file question

### ISSUE THREAD

**Issue by AOCjcarr** [Chicago/lead-safe-api-docs#12]
Reviewing the response file, it appears the one missing element would be a "Error message"  Essentially this would be blank for most calc's however it would be good to have some level of a qualified response that has details for any reason why a calc returned with no information or there was an error calculating.
In similar projects we have found this is typically related to 1) a specific expected data element missing  2) unexpected data in the filed ( ie: BLL = TNP rather than a value).

For the EMR, we can display this additional message when it is returned so the staff is aware if the result may be impacted by a issue with the calculation.   Otherwise they would just see the results returned, or that nothing returns and they have no idea why, which will decrease confidence in the calc, or possibly they incorrectly assume returned value is final if there was missing info.

**Comment by tomschenkjr** [comment]
Thanks, this makes a lot of sense.

Also, for better transparency for our upcoming work, we've moved the roadmap for the API to [the wiki page](https://github.com/Chicago/lead-safe-api-docs/wiki). We have not worked on "robust error messages" yet, instead we've simply relying on default error messages being passed along so far.

This one seems to make sense to include in more robust error messages to pass back to you / users. Other folks can also chime-in on thoughts.

(Thanks for chiming-in on GitHub. Feel free to open issues / communicate though this since it's how we organize the project).
