### ISSUE TITLE
Eligibility criteria & process for new institutions

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#2]
Right now, there is stock language on the eligibility of health systems and a faux-link to a sign-up form. In reality, we need to determine what institutions are eligible, the actual sign-up process, and any supporting materials that the institutions are required to submit.

**Comment by RaedMan** [comment]
Create Eligibility Intake Form (draft):

**1. Name of Health Network**
(see list below for drop-down menu options and consider other [FQHCs found on the portal](https://data.cityofchicago.org/Health-Human-Services/Public-Health-Services-Chicago-Primary-Care-Commun/cjg8-dbka/data))

**2. Clinical Point of Contact**
a. Name
b. Title
c. National Provider Identifier
d. Illinois Physician License (Should we include nurses, NPs, etc)
e. Contact Information: Address, Telephone, Email

**3. Technical Point of Contact**
a. Name
b. Title
c. Contact Information: Address, Telephone, Email

**4. Eligibility Criteria**
I have read the Eligibility Criteria and certify that this institution meets the minimum standards.

**5. Terms of Service**
I have read the Terms of Service
I accept the Terms and Service
I do not accept the Terms of Service


**Hospitals within Chicago for drop down:**
1. Advocate Christ Medical Center, 4440 West 95th Street
2. Advocate Illinois Masonic Medical Center, 836 West Wellington
3. Advocate Trinity Hospital, 2320 East 93rd Street
4. Ann & Robert H. Lurie Children's Hospital of Chicago, 225 E. Chicago Avenue
5. Holy Cross Hospital, 2701 West 68th Street
6. Jackson Park Hosp. Foundation, 7531 Stony Island Avenue
7. John H. Stroger Hospital of Cook County, 1901 West Harrison Street
8. LaRabida Children's Hospital, 6501 S. Promontory Drive
9. Little Company of Mary Hospital and Health Care Centers, 2800 West 95th Street
10. Loretto Hospital, 645 South Central Avenue
11. Louis A. Weiss Memorial Hospital, 4646 North Marine Drive
12. Mercy Hospital & Medical Center, 2525 South Michigan Avenue
13. Methodist Hospital of Chicago, 5025 North Paulina Street
14. Mount Sinai Hospital Medical Center, 2750 W. 15th Street
15. Northwestern Memorial Hospital, 211 East Ontario
16. Norwegian American Hospital, 1044 North Francisco Avenue
17. Presence Our Lady of the Resurrection Medical Center, 5645 West Addison Street
18. Presence Resurrection Medical Center, 7435 West Talcott Avenue
19. Presence Saint Francis Hospital, 355 Ridge Avenue
20. Presence Saint Joseph Hospital Chicago, 2900 North Lake Shore Drive
21. Presence Saint Mary Of Nazareth Hospital, 2233 West Divison Street
22. Presence St. Elizabeth's Hospital, 1431 North Claremont
23. Provident Hospital of Cook County, 500 East 51st Street
24. Roseland Community Hospital, 45 West 111th Street
25. Rush University Medical Center, 1653 West Congress Parkway
26. Shriners Hospitals for Children - Chicago, 2211 North Oak Park
27. South Shore Hospital, Corp., 8012 South Crandon Ave.
28. St. Anthony Hospital, 2875 West 19th Street
29. St. Bernard Hospital, 326 West 64th Street
30. Swedish Covenant Hospital, 5145 North California Avenue
31. Thorek Memorial Hospital, 850 West Irving Park Road
32. University of Chicago Medical Center, 5841 South Maryland
33. University of Illinois Medical Center at Chicago, 740 West Taylor Avenue

Policy for approvals and next steps in discussion, but approvals may need to occur as pilots one-one-at-a-time.

**Comment by tomschenkjr** [comment]
Thanks, Raed. This looks like a good first draft. We may want a sentence or two of who the clinical point of contact should be and who the technical point of contact should be. DoIT can draft the latter if CDPH can draft the former.

@wesleycoates - you mentioned the [list on the portal](https://data.cityofchicago.org/Health-Human-Services/Public-Health-Services-Chicago-Primary-Care-Commun/cjg8-dbka/data) may be out-of-date. Is there an updated list? I've also [looked on data.gov](https://catalog.data.gov/dataset?q=fqhc&sort=score+desc%2C+name+asc&as_sfid=AAAAAAWJgh6Znu2LqbgTUh2WtdourOnz5pAVo9HQ4o6thDxcFywJdM80zGxwyR1SMxAAfmLOOIm839DbKYsoN8bS62CvJuBGW8oAq-2a7BaQ9RPxrN-RjxkIqlRzebpvqjnzvV8%3D&as_fid=e8ed056c17e57762105fe6a2372433ab3af76de9), but don't think I see a federal dataset, unfortunately.

**Comment by wesleycoates** [comment]
Nicely done Raed.  Yes Tom, that list is certainly out of date (2014), but somewhat actionable.  Raed, Sheri Cohen curated that list based on [something similar from HRSA.](https://findahealthcenter.hrsa.gov/index.html).  I am not familiar enough with the criteria to know what qualifies, but we can check around and see if we can get that updated.

**Comment by RaedMan** [comment]
**Re: 2.  Clinical Point of Contact (draft)**
The clinical point of contact should be a physician licensed to practice medicine in all its branches as defined by the [Illinois Medical Practice Act of 1987](http://ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1309&ChapAct=225%C2%A0ILCS%C2%A060/&ChapterID=24&ChapterName=PROFESSIONS+AND+OCCUPATIONS&ActName=Medical+Practice+Act+of+1987.).

The physician shall be an authority or in a senior management position at their healthcare facility or program (the healthcare facility and program as defined by the [Illinois Department of Public Health](http://www.dph.illinois.gov/topics-services/health-care-regulation/facilities)). The physician is expected to be a champion for the lead safe project, as well as willing to provide support or commit resources on behalf of the healthcare facility and program. This physician is generally in charge of medical matters and often is the superior of other physicians, but may also be in charge of other professional groups and areas of responsibility. In many healthcare facilities and programs, this person may have the title of the most senior physician, (e.g., chief physician, head physician, physician in chief, chief of medicine, chief medical officer, chief resident, chief of staff, etc.,) or they may also have the title of the most senior physician of a particular department (e.g., department chair) but they don't necessarily require any the titles noted in the above examples.

**Comment by tomschenkjr** [comment]
@RaedMan - for NPI and IPL, is there a minimum length for the identifier? Is it just numeric or are there letters, too?

I can add some validation to the form to make sure length requirements are being met.

**Comment by tomschenkjr** [comment]
I've mocked-up an initial draft of the form based on @RaedMan initial draft. Attached is a screenshot (click for a larger image) of the code that is currently sitting on `issue2` branch. Let me know if there are any changes that are needed, if not, I think we can share this with others.

Before this can be finalized, will need the correct email address to use.

![localhost-8000-signup- laptop with touch](https://user-images.githubusercontent.com/1639121/31643643-66bbcac4-b2b7-11e7-95cf-0fe0574fa26a.png)

**Comment by RaedMan** [comment]
@tomschenkjr Great work! As for your questions:

- NPI is a 10-digit numeric identifier
- IL License Number is a 9-digit numeric identifier that begins with 036-XXXXXX (the 036 indicates they have a Permanent Physician License so it would be good to have that pre-filled)
- Email - Awaiting approval for HealthyHomes@cityofchicago.org. Submitted ARF. It will be forwarded to me for the time-being.

**Comment by RaedMan** [comment]
Update: email address HealthyHomes@cityofchicago.org is approved.

**Comment by tomschenkjr** [comment]
I've updated the form and created a pull request #15 that documents the changes so far. Please take a look as I've uploaded the screenshots of the application and how an application will appear in email.

This is a pretty complete draft, but not entirely done with this issue. When we're ready to deploy, still need the following changes:
  - [ ] Need to update links to the terms of service and eligibility requirements.
  - [x] May want to improve the look of the dropdown box (`select input`)
  - [ ] The subject line is "Test Submission: Lead Safe API Request". This should remove "Test Submission" when it's no longer in testing.

**Comment by tomschenkjr** [comment]
Also, I should note that HealthyHomes@cityofchicago.org will be sent all the email (in the To: line) while developers@cityofchicago.org (which DOIT can access) will be CC'd.

**Comment by RaedMan** [comment]
@wesleycoates can the ARF be amended for HealthyHomes@cityofchicago.org to include developers@cityofchicago.org or @tomschenkjr is this something you all can do?

**Comment by RaedMan** [comment]
Everything looks great - thanks @tomschenkjr

**Comment by tomschenkjr** [comment]
No need for an ARF. DOIT already has access to that email (we use it, for example, as notifications for registering with the Open311 API). You’ll still control the process, we just get a heads-up so we’re also aware and can plan accordingly.

**Comment by wesleycoates** [comment]
I bet Christine has acted on the ARF already -- meaning Unisys is already
creating healthyhomes@cityofchicago.org

Check with her tomorrow and see -- if not, she just needs to create another
through another ARF

**Comment by RaedMan** [comment]
@wesleycoates Sorry, I didn't mean to imply we need to create developers@cityofchicago.org, just that when a message is sent to healthyhomes@cityofchicago.org, besides me, that it also gets sent to the developers email. I thought the ARF was needed.

**Comment by tomschenkjr** [comment]
The main remaining item left for this issue is eligibility requirements. The current draft of the form points to eligibility requirements separately from terms of service. Are these the same or separate? If separate, what are the eligibility requirements?

**Comment by tomschenkjr** [comment]
@RaedMan - I've moved this particular issue to be finished in v0.6.0 of the API (the next release). We will need the eligibility requirements so we can list them on the webpage.

Would it be possible to get the eligibility requirements before January 19th?

**Comment by RaedMan** [comment]
@tomschenkjr Yes, and the eligibility requirement for the clinical side is an amalgam of the form above plus the piece about the draft Clinical Point of Contact paragraph from above. I can fuse it into written form (ie, must have a license, must be a hospital listed below, etc) and can definitely have it done this week.

A missing component is a Technical piece and what is needed to make it happen. Perhaps referencing the repos needed may suffice, but this may vary across health systems. Borrowing from the RWJF grant were as follows if this works:

**Scope of Work**
EHR trigger to notify at-risk patients/families against a geographic database of Chicago lead risk. EHR trigger is based on age and pregnancy status patient list of patient at-risk to be notified in at the patient office visit and in real-time with a trigger notification alert. CDPH maintains a geographical listing of at-risk properties.

**Deliverables**
CDPH will provide access to an updated database where queries are made to the server based on child patient age and/or a mother’s prenatal visits and patient address. Queries handled to include, triggers, XML file, and Clinical Decision Support. At risk notification to provider or care coordinators to communicate to the patient.

**Git Hub Link Codes**
Model
ETL
API

**Anticipated Resources**
Professional Services, Project Management, IT Development, Licenses, etc. All costs for development, programming and support should be planned for and are borne by the healthcare facility and not by the City of Chicago.

Not sure about that last section on resources.

**Comment by RaedMan** [comment]
**Eligibility Criteria**

In order to access the Lead Safe API, you must comply with the following criteria:

**1. Must be a Healthcare Facility or Program as [Defined by the Illinois Department of Public Health](http://www.dph.illinois.gov/topics-services/health-care-regulation/facilities) in the City of Chicago.**
See the list of qualified facilities in Chicago.

**2. Healthcare Facility Must Have a Clinical Point of Contact**
The clinical point of contact should be a physician licensed to practice medicine in all its branches as defined by the [Illinois Medical Practice Act of 1987](http://ilga.gov/legislation/ilcs/ilcs3.asp?ActID=1309&ChapAct=225%C2%A0ILCS%C2%A060/&ChapterID=24&ChapterName=PROFESSIONS+AND+OCCUPATIONS&ActName=Medical+Practice+Act+of+1987). The physician shall be an authority or in a senior management position at their healthcare facility or program (the healthcare facility and program as defined by the Illinois Department of Public Health. The physician is expected to be a champion for the lead safe project, as well as willing to provide support or commit resources on behalf of the healthcare facility and program. This physician is generally in charge of medical matters and often is the superior of other physicians, but may also be in charge of other professional groups and areas of responsibility. In many healthcare facilities and programs, this person may have the title of the most senior physician, (e.g., chief physician, head physician, physician in chief, chief of medicine, chief medical officer, chief resident, chief of staff, etc.,) or they may also have the title of the most senior physician of a particular department (e.g., department chair) but they don't necessarily require any the titles noted in the above examples.

**3. Healthcare Facility Must Have a Technical Point of Contact**
The technical point of contact should be someone authorized to make changes to their Electronic Health Record (EHR) either through internal facility staff or external contractors and have a working understanding of HIPAA privacy and security rules, [Health Information Technology (HIT) Standards](https://www.healthit.gov/policy-researchers-implementers/2015-edition-final-rule) and [Application Programming Interfaces in HIT](https://www.healthit.gov/api-education-module/story_html5.html). The following describes the technical scope of work and expectations involved, but is not necessarily limited to these:

_Scope of Work_
EHR trigger to notify at-risk patients/families against a geographic database of Chicago lead risk. EHR trigger is based on age and pregnancy status patient list of patient at-risk to be notified in at the patient office visit and in real-time with a trigger notification alert. CDPH maintains a geographical listing of at-risk properties.

_Deliverables_
The Chicago Department of Public Health will provide access to an updated database where queries are made to the server based on child patient age and/or a mother’s prenatal visits and patient address. Queries handled to include, triggers, XML file, and Clinical Decision Support. At risk notification to provider or care coordinators to communicate to the patient.

_Git Hub Link Codes_
- [Mode](https://github.com/Chicago/lead-model)l
- [ETL](https://github.com/Chicago/lead-etl)
- [Lead Safe API](https://github.com/Chicago/lead-safe-api-docs)

_Anticipated Resources_
Professional Services, Project Management, IT Development, Licenses, etc. Note that all costs for development, programming and support should be planned for and will be borne by the healthcare facility and not by the City of Chicago.

**4. Privacy Official**
Under HIPAA (Health Insurance Portability and Accountability Act of 1996) the healthcare facility's privacy official (the privacy official may have other titles and duties in addition to his/her privacy official designation in a typical healthcare facility setting) shall oversee all Lead Safe API development, implementation, maintenance and compliance to the healthcare facility's privacy policies in accordance with applicable federal, state, and local laws. HIPAA for purposes of this document includes HIPAA, HITECH and Omnibus requirements.

**Comment by RaedMan** [comment]
@tomschenkjr @geneorama @wesleycoates Regarding eligibility, this draft can go up after "3. Healthcare Facility Must Have a Technical Point of Contact" component is reviewed because I wasn't sure how in depth it should go. Also, if this goes up, should we add "DRAFT" somewhere until it goes through the process of approvals?
