### ISSUE TITLE
Add "expected due date" field for expecting mothers

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/lead-safe-api-docs#36]
We will need to render some scores based on pregnant women when we are trying to assess the risk of a child in prenatal development. However, this causes an issue because the mother's records are sent to the API. 

Talking with Alliance, we determined the best method to identify a pregnant woman is to submit the `expected_due_date` for the mother and check if the record is in the future. If we determine it _is_ at a future date, then we will need to ignore the `date_of_birth` and `lab` results.

The `expected_due_date` field should be a date field, e.g, `YYYY-MM-DD` with no timestamp. It may be blank.

**Comment by geneorama** [comment]
Recapping my understanding of subsequent discussions:

Background: the API is exclusively for children under 1 year of age, including pregnant mothers. The birth date / delivery date is not used in producing the prediction, it is only used to determine if we provide a response (as of `1.0.0rc-3`). 

If there is an expected due date, then we are dealing with a expected mother and we should provide a score (regardless of when the expected due date is relative to today). Otherwise we should rely on the birth date to determine if the patient is under 1  year of age.

Is this correct?

**Comment by tomschenkjr** [comment]
Correct. Also see lead-prediction-runner#76 for the workflow diagram. But yes, that aligns to the plan.

**Comment by geneorama** [comment]
Great, I'm putting that into a new branch called rc3.

Forgot to add earlier, that we ignore labs if there's an expected date.

**Comment by tomschenkjr** [comment]
I created two tasks. This is a duplicate of #35, so closing this in favor of the other issue.
