### ISSUE TITLE
Interpreting Risk Levels Section - Edits for rc3

### ISSUE THREAD

**Issue by geneorama** [Chicago/lead-safe-api-docs#39]
Here's a link to the section in question: https://chicago.github.io/lead-safe-api-docs/api/#interpreting-risk-levels

I have a few questions
 - Do we need this section at all? Perhaps the focus of this documentation should be narrowly limited to "how to use the API".
 - If we keep this section, I personally think it belongs on the main page, not in the API section.
 - The language makes it sound like we're reporting on actual BLL levels rather than the risk of having a high BLL.  So, at a minimum I would change this to "When the API identifies elevated risk of elevated blood-lead levels".  (yes the double "elevated" is awkward, I didn't have something better)
 - It also recommends further testing, but I think our recommendation is actually remediation / inspections. 

With regard to the text within the note:
 - This link is broken: https://www.cityofchicago.org/city/en/depts/cdph/provdrs/inspections_and_permitting/svcs/apply_for_financialassistanceforleadabatement.html 
 - We still have INSERT NAME OF NON-PROFITS, so we should insert the names of the non profits!

**Comment by RaedMan** [comment]
Thanks @geneorama 

Good catch - I agree with re-writing. I think it makes sense to stay here, because others may be exploring it for non-technical reasons, and may want to see the entire workflow. I think giving the options of what we designed in terms of recommendations could be provided for other health systems. Here's a draft, we can confirm internally in April:
- "When the API identifies a risk of lead poisoning, healthcare providers may check past and/or conduct further lead blood tests, discuss risks of lead poisoning, distribute Lead Safe FAQ, and request a visual inspection from CDPH."

Text in Note
- Updated link: https://www.cityofchicago.org/city/en/depts/cdph/provdrs/healthy_homes/svcs/apply_for_financialassistanceforleadabatement.html

- Delete:  "Local non-profits, such as (INSERT NAME OF NON-PROFITS)"

- Add CDPH Tele: "Families may dial 311 for further assistance or contact CDPH at 312-747-LEAD(5323).

**Comment by geneorama** [comment]
Thanks @RaedMan that was easy enough (with your comments that is).
