### ISSUE TITLE
Description of high / low scores for EHR "info" buttons

### ISSUE THREAD

**Issue by geneorama** [Chicago/lead-safe-api-docs#50]
Develop language for Alliance and others that describes what a "high" or "low" scores mean. 

I think we need to answer: 
 - Where does the belong in the documentation
 - For new members is the description a requirement / suggestion / FYI 
 - Should we provide a mechanism (perhaps an email alert?) for changes to the description
 - Who is responsible for drafting the initial language, and who maintains it on an ongoing basis

@RaedMan please feel free to edit this issue description

**Comment by RaedMan** [comment]
- Where does the belong in the documentation:
Perhaps with our API returns for High, Low, Null because they explain what they mean.

- For new members is the description a requirement / suggestion / FYI:
That is up to the EHR system and hospital to make that decision since it is a feature that is entirely under their control.

- Should we provide a mechanism (perhaps an email alert?) for changes to the description:
Not necessary since this is not part of the API. We will not maintain ongoing edits because each hospital's respective EHR systems will not allow a way for us to maintain version control since we can't read changes from any EHR info button. We will provide an initial template as a service and recommend that they use it for similar info button features in various EHRs when they adopt this tool.

- Who is responsible for drafting the initial language, and who maintains it on an ongoing basis:
I drafted initial language:
1. High Risk indicates this patient is more likely to be at risk to be lead paint poisoned compared to the baseline Alliance patient population.
2. Low Risk indicates this patient is less likely to be at risk to be lead paint poisoned compared to the baseline Alliance patient population.
3. Patient already has high BLL ≥ 5mcg/dL in previous labs. Model was not run and no risk score was generated. Recommend review past notes.

I'll add @avishekrk and AllianceChicago's final edits here if that is appropriate.

**Comment by geneorama** [comment]
> That is up to the EHR system and hospital to make that decision since it is a feature that is entirely under their control.

This sounds to me like an FYI to health centers about how they might want to describe the resulting message in the EHR. 

> I'll add @avishekrk and AllianceChicago's final edits here if that is appropriate.

@RaedMan yes, I think it would be a good idea to document the edits here. I can open a branch and insert the language once it's finalized by you, Avishek, and Alliance.

**Comment by RaedMan** [comment]
Removing _3. Patient already has high BLL ≥ 5mcg/dL in previous labs. Model was not run and no risk score was generated. Recommend review past notes._

There is no mechanism developed to execute this now, but perhaps in a future version, it can be added into the workflow.

**Comment by RaedMan** [comment]
@avishekrk @AOCjcarr @geneorama 

The responses were edited from the drafts on issue #38 that was closed in March because the LOW RISK statement was not clear. Reference Chicago/lead-model/issues/9 for finalized response approved on 8/21 provided here for ease:

risk_score (numeric value)
risk_score_notes **HIGH RISK: Refer for lead paint visual home inspection to Chicago Department of Public Health at 312-747-LEAD(5323)**

risk_score (numeric value)
risk_score_notes **LOW RISK: Discuss lead exposure prevention anticipatory guidance.**

**Comment by geneorama** [comment]
Closing because we are not putting info button descriptions into the project, mainly because we can't control it.
